DROP ROLE IF EXISTS "vef2-user-v2";
CREATE USER "vef2-user-v2" WITH ENCRYPTED PASSWORD '123';
GRANT ALL PRIVILEGES ON DATABASE verkefni2db TO "vef2-user-v2";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "vef2-user-v2";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "vef2-user-v2";
